import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "./components/Header/Index";

const roboto = Roboto({
  variable: "--font-roboto",

  weight: ["300", "400", "500", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt" className={`${roboto.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <>
          <Providers>
            <Header />
            {children}
          </Providers>
        </>
      </body>
    </html>
  );
}
